apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: api-ingress-network-policy
  namespace: todo-app
spec:
  podSelector:
    matchLabels:
      app: api
  ingress:
  - from:
    - podSelector: {}
    ports:
      - port: 5500
        protocol: TCP
      - port: 5500
        protocol: UDP
