apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ui-egress-network-policy
  namespace: todo-app
spec:
  podSelector:
    matchLabels:
      app: ui-todo
  egress:
  - ports:
    - port: 80
    to:
    - podSelector: {}
      namespaceSelector: {}
  policyTypes:
  - Egress

