enabled: true

api:

  container:
    image: todo-api
    repository: gcr.io/todo-app-340708
    imagePullPolicy: "Always"
    port: 5500

  readinessProbe:
    httpGet:
      path: /tasks
      port: 5500
    initialDelaySeconds: 15
    periodSeconds: 5

  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 50

  service:
    type: LoadBalancer
    port: 5050

  ingress:
      ipBlock: 0.0.0.0/0
      port: 5500
      protocol: TCP

