{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  namespace: {{ .Values.global.namespace }}
  annotations:
    kubernetes.io/ingress.global-static-ip-name: {{ .Release.Name }}-ip
    kubernetes.io/ingress.class: {{ .Values.ingress.annotations.ingressClass | quote }}
    ingress.kubernetes.io/enable-cors: {{ .Values.ingress.annotations.enableCors | quote | quote }}
    ingress.kubernetes.io/cors-allow-methods: {{ .Values.ingress.annotations.corsAllowMethods | quote }}
    ingress.kubernetes.io/cors-allow-origin: {{ .Values.ingress.annotations.corsAllowOrigin | quote }}
spec:
  tls:
  {{- range .Values.ingress.tls }}
    - secretName: {{ .secretName }}
  {{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ .host }}
    http:
      paths:
        - path: {{ .http.paths.path }}
          pathType: {{ .http.paths.pathType }}
          backend:
            service:
              name: {{ .http.paths.backend.service.name }}
              port:
                number: {{ .http.paths.backend.service.port.number }}
  {{- end }}
{{- end }}