{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  namespace: {{ .Values.global.namespace }}
  annotations:
    kubernetes.io/ingress.global-static-ip-name: {{ .Release.Name }}-ip
    kubernetes.io/ingress.class: {{ index .Values ".ingress.annotations.kubernetes.io/ingress.class" }}
    ingress.kubernetes.io/enable-cors: {{ index .Values ".ingress.annotations.ingress.kubernetes.io/enable-cors" }}
    ingress.kubernetes.io/cors-allow-methods: {{ index .Values ".ingress.annotations.ingress.kubernetes.io/cors-allow-methods" }}
    ingress.kubernetes.io/cors-allow-origin: {{ index .Values ".ingress.annotations.ingress.kubernetes.io/cors-allow-origin" }}
spec:
  tls:
  {{- range .Values.ingress.tls }}
    secretName: {{ .secretName }}
  {{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    host: {{ .host }}
    http:
      paths:
        - path: {{ .http.paths.path }}
          pathType: {{ .http.paths.pathType }}
          backend:
            service:
              name: {{ .http.paths.backend.service.name }}
              port:
                number: {{ .http.paths.backend.service.port.number }}
  {{- end }}
{{- end }}