{{- if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: {{ .Values.global.db.name }}-deployment
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.db.replicaCount }}
  selector:
    matchLabels: 
      app: {{ .Values.global.db.name }}
  template: 
    metadata: 
      labels:
        app: {{ .Values.global.db.name }}
    spec:
      containers: 
      - name: {{ .Release.Name }}-{{ .Values.global.db.name }}
        image: {{ .Values.db.container.image }}:{{ .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.db.container.imagePullPolicy }}
        ports: 
        - containerPort: {{ .Values.db.container.port }}
        env:
        {{- range .Values.global.config.data }}
          - name: {{ .key }}
            valueFrom:
              configMapKeyRef:
                name: {{ $.Values.global.config.name }}
                key: {{ .key }}
        {{- end }}
        {{- range .Values.global.secret.data }}
          - name: {{ .key }}
            valueFrom:
              secretKeyRef:
                name: {{ $.Values.global.secret.name }}
                key: {{ .key }}
        {{- end }}
        volumeMounts: 
        - name: {{ .Values.db.volume.name }}
          mountPath: /var/lib/mysql 
      volumes: 
      - name: {{ .Values.db.volume.name }}
        persistentVolumeClaim: 
          claimName: {{ .Values.global.db.name }}-pv-claim
{{- end }}