{{- if .Values.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.secret.name }}
  namespace: {{ .Values.global.namespace }}
type: {{ .Values.global.secret.type }}
data:
{{- range .Values.global.secret.data }}
  {{ .key }}: {{ .value }}
{{- end}}
{{- end }}
