enabled: true

ui:

  container:
    image: todo-ui
    repository: gcr.io/todo-app-340708
    imagePullPolicy: "Always"
    port: 80

  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 50

  service:
    type: LoadBalancer
    port: 5051

  ingress:
      ipBlock: 0.0.0.0/0
      port: 80
      protocol: TCP