apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: db-deployment
  namespace: todo-app
spec:
  replicas: 1 
  selector:
    matchLabels: 
      app: db
  template: 
    metadata: 
      labels:
        app: db 
    spec:
      containers: 
      - name: todo-db 
        image: mariadb:10.3.5
        imagePullPolicy: "IfNotPresent"
        ports: 
        - containerPort: 3306
        env: 
        - name: MYSQL_USER
          valueFrom: 
            configMapKeyRef: 
              name: db-config 
              key: MYSQL_USER
        - name: MYSQL_DATABASE
          valueFrom: 
            configMapKeyRef: 
              name: db-config 
              key: MYSQL_DATABASE
        - name: MYSQL_ROOT_PASSWORD 
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_PASSWORD 
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: MYSQL_PASSWORD
        volumeMounts: 
        - name: data
          mountPath: /var/lib/mysql 
      volumes: 
      - name: data
        persistentVolumeClaim: 
          claimName: db-pv-claim
