apiVersion: v1
kind: PersistentVolumeClaim  
metadata:
  name: mariadb-pv-claim 
  namespace: todo-app
spec:
  storageClassName: microk8s-hostpath 
  accessModes: 
  - ReadWriteMany 
  resources: 
    requests:
      storage: 5Gi

