apiVersion: v1
kind: PersistentVolumeClaim  
metadata:
  name: mariadb-pv-claim 
  namespace: todo-app
spec:
  accessModes: 
  - ReadWriteOnce 
  resources: 
    requests:
      storage: 5Gi

