apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: angular-deployment 
  labels: 
    app: angular
spec: 
  replicas: 3 
  selector: 
    matchLabels: 
      app: angular
  template: 
    metadata: 
      labels: 
        app: angular
    spec: 
      containers: 
      - name: nginx-runner
        image: localhost:32000/angular:v1 
        ports: 
          - containerPort: 80

