apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: ui-deployment 
  namespace: todo-app
spec:
  selector: 
    matchLabels: 
      app: ui
  template: 
    metadata: 
      labels: 
        app: ui
    spec: 
      containers: 
      - name: todo-ui
        imagePullPolicy: Always
        image: gcr.io/todo-app-339413/todo-ui:v1.0
        ports: 
          - containerPort: 80

