{{- if .Values.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.global.ui.name }}-ingress-network-policy
  namespace: {{ .Values.global.namespace }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.global.ui.name }}
  ingress:
  - from:
    - ipBlock:
        cidr: {{ .Values.ui.ingress.ipBlock }}
    ports:
      - port: {{ .Values.ui.ingress.port }}
        protocol: {{ .Values.ui.ingress.protocol }}
{{- end }}
