{{- if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.config.name }}
  namespace: {{ .Values.global.namespace }}
data:
{{- range .Values.global.config.data }}
  {{ .key }}: {{ .value }}
{{- end}}
{{- end }}