{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.name }}-service
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.db.service.type }}
  ports:
  - protocol: {{ .Values.db.service.protocol }}
    port: {{ .Values.db.service.port }}
    targetPort: {{ .Values.db.container.port }}
  selector:
    app: {{ .Values.db.name }}
{{- end }}