{{- if .Values.enabled }}
apiVersion: v1
kind: {{ .Values.db.volume.pvc.kind }}
metadata:
  name: {{ .Values.db.name }}-pv-claim
  namespace: {{ .Release.Namespace }}

spec:
  accessModes:
  - {{ .Values.db.volume.pvc.accessMode }}
  resources:
    requests:
      storage: {{ .Values.db.volume.pvc.storage }}
{{- end }}

