{{- if .Values.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.global.api.name }}db-egress-network-policy
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.global.api.name }}
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: {{ .Values.global.api.name }}
    ports:
      - port: 3306
        protocol: TCP
  policyTypes:
  - Egress
{{- end }}


