{{- if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.global.api.name }}-deployment
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.global.api.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.global.api.name }}
    spec:
      containers:
        - name: {{ .Release.Name }}-{{ .Values.global.api.name }}
          imagePullPolicy: {{ .Values.api.container.imagePullPolicy }}
          image: {{ .Values.api.container.repository }}/{{ .Values.api.container.image }}:{{ .Chart.AppVersion }}
          ports:
            - containerPort: {{ .Values.api.container.port }}
          readinessProbe:
            httpGet:
              path: {{ .Values.api.readinessProbe.httpGet.path }}
              port: {{ .Values.api.readinessProbe.httpGet.port }}
            initialDelaySeconds: {{ .Values.api.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.api.readinessProbe.periodSeconds }}
          env:
          {{- range .Values.global.config.data }}
            - name: {{ .key }}
              valueFrom:
                configMapKeyRef:
                  name: {{ $.Values.global.config.name }}
                  key: {{ .key }}
          {{- end }}
          {{- range .Values.global.secret.data }}
            - name: {{ .key }}
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.global.secret.name }}
                  key: {{ .key }}
          {{- end }}
{{- end }}