apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: todo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: todo-api
          image: localhost:32000/todo-api:latest
          ports:
            - containerPort: 5500
          env: 
          - name: MYSQL_USER
            valueFrom: 
              configMapKeyRef: 
                name: db-config 
                key: MYSQL_USER
          - name: MYSQL_DATABASE
            valueFrom: 
              configMapKeyRef: 
                name: db-config 
                key: MYSQL_DATABASE
          - name: MYSQL_PASSWORD 
            valueFrom:
              secretKeyRef: 
                name: db-secret 
                key: MYSQL_PASSWORD
