apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: api-scaler
  namespace: todo-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-deployment
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
